### ISSUE TITLE
Ability to /u admin updateplugin <plugin> <branch>

### ISSUE THREAD

**Issue by alisolarflare** [TBMCPlugins/ButtonCore#23]
I've been reading up on Git Branching models, and I'm interested in toying around with a development branch. Is it possible to specify which branch jitpack compiles? Because that would allow a more release type schedule.
![image](https://cloud.githubusercontent.com/assets/18705807/20760568/64281cec-b6ee-11e6-9f56-dc2dc303c25b.png)

**Comment by NorbiPeti** [comment]
Yes, it's possible, pretty easily. Though, how would this work in our case? At least at the moment we're pretty much uploading the latest dev version. Though I guess we could use the dev versions for the local test servers...

**Comment by alisolarflare** [comment]
AAYYYYY
